version: '3'

services:
  httpd:
    image: pravrang/httpd2.4.25
    ports:
      - 80:80
      - 443:443
    volumes:
      - "vol_logs:/opt/httpd/logs"
      - "vol_logs:/opt/shared" 
    networks:
      docker1:
        aliases:
          - httpd
    dns_search: webmidlabs.com
    
  tomee:
    image: pravrang/tomee7.0
    expose:
      - "8080"
      - "8443"
      - "8009"
    volumes:
      - "vol_logs:/opt/tomee/webapps"
      - "vol_logs:/opt/tomee/logs"
      - "vol_logs:/opt/shared" 
    networks:
      docker1:
        aliases:
          - tomee
    dns_search: webmidlabs.com

volumes:
  vol_logs:

networks:
  docker1:

  